travis:
  secure:
    BINSTAR_TOKEN: oN9Oq26BT4M//YMhH4wfMXXi71sOSUejtxdJX1WZPGPyy9YAA3D5VioOhOqr5PvK7YtoLkq7hVGU9MOYPgHo7Ehfy1ijEfn34S12uESCu7gVoJr5nNODvDsZpkP+byokNHFMr0o/NcX08JCf1a7iCPcPtMmn3vp0zCvt4MhMbEPYTG7nXLi4WqWAYDLu2IWXhIM1ZJtv0D3l4U3dHHruHbFIH662KtZzO3R+MhFxGikVL0OjG+/IZckDx9ByEIiwb0AzHAktsYJXtyZtJ3Qfuk7oJILp2xMv19d8gbyLzaGHOoNEiHIHt6hfPixl5eLNpaBTEdKlttx4gsoDtFIpEdrjeiczyI6gslGyVuVDW/OeKUjE7q7O9uo4SJyzTUkGyiaddJyVR3f7+H2llD21Ub9b5rDjSUpiAy9drbks8jggCv+QqEC4i1jE1cTBch/4FmREzamHiwktup9Rs5NRzs/1pAd+m5CtB6lpAkBqLkT7/dzg9Tmo6vg01ha4pwdQjT9dJSDmRZeveJUNOMemjAGV4sqXu0KI4oQSvYVDk2joAfQg/m/PNQKYzQRjA90QyD597kQlDYHAlf/R+SP+CFmxy0OdQ0BnNMMpzpfXREco2n5VT1hfOUjB38NmB2nw/+wPytLY728hzgRNEJhX+RKpibj0T42vGd/2tuZe/+o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
